import { useMemo, useState } from "react"
import { CircleOff, Pause, Play, Search } from "lucide-react"
import { Badge } from "../../components/ui/badge"
import { Button } from "../../components/ui/button"
import { Drawer } from "../../components/ui/drawer"
import { EmptyState, PageHeader } from "../../components/ui/page"
import { events } from "../../mock/data"
import type { AnalyticsEvent } from "../../types/analytics"

export function EventsPage() {
  const [live, setLive] = useState(true)
  const [query, setQuery] = useState("")
  const [kind, setKind] = useState("All types")
  const [selected, setSelected] = useState<AnalyticsEvent | null>(null)
  const visible = useMemo(() => events.filter((e) => (kind === "All types" || e.kind === kind) && e.name.includes(query.toLowerCase())), [kind, query])
  return <>
    <PageHeader title="Event stream" description="Inspect behavioral signals and authoritative commerce facts as they enter analytics." badge={<Badge tone={live ? "success" : "neutral"} dot>{live ? "Streaming" : "Paused"}</Badge>} actions={<Button variant="outline" onClick={() => setLive(!live)}>{live ? <Pause size={14} /> : <Play size={14} />}{live ? "Pause stream" : "Resume stream"}</Button>} />
    <div className="panel mb-4 flex flex-wrap gap-2 p-3"><div className="relative min-w-[230px] flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search event name or ID" className="h-9 w-full rounded-lg border bg-background pl-9 pr-3 text-xs" /></div><select value={kind} onChange={(e) => setKind(e.target.value)} className="h-9 rounded-lg border bg-background px-3 text-xs"><option>All types</option><option>Behavior</option><option>Commerce</option></select><select className="h-9 rounded-lg border bg-background px-3 text-xs"><option>All sources</option><option>web-sdk</option><option>medusa-webhook</option></select><select className="h-9 rounded-lg border bg-background px-3 text-xs"><option>All states</option><option>Valid</option><option>Warning</option><option>Invalid</option></select></div>
    {visible.length ? <section className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-[11px]"><thead className="bg-muted/40 text-muted-foreground"><tr>{["Event name","Timestamp","Session","Journey","Source","Type","Validation","Authority","Projection"].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{visible.map((event,index) => <tr key={`${event.name}-${index}`} onClick={() => setSelected(event)} className="cursor-pointer border-b last:border-0 hover:bg-muted/30"><td className="px-4 py-3 font-mono text-foreground">{event.name}</td><td className="px-4 font-mono text-muted-foreground">{event.timestamp}</td><td className="px-4 font-mono text-primary">{event.session}</td><td className="px-4 font-mono">{event.journey}</td><td className="px-4">{event.source}</td><td className="px-4"><Badge tone={event.kind === "Commerce" ? "commerce" : "behavior"}>{event.kind}</Badge></td><td className="px-4"><Badge tone={event.validation === "Valid" ? "success" : event.validation === "Warning" ? "warning" : "danger"}>{event.validation}</Badge></td><td className="px-4">{event.authority}</td><td className="px-4"><Badge tone={event.projection === "Degraded" ? "danger" : event.projection === "Live / Provisional" ? "primary" : "neutral"}>{event.projection}</Badge></td></tr>)}</tbody></table></div></section> : <EmptyState icon={<CircleOff size={20} />} title="No events match these filters" detail="Try another event type, source or search phrase." />}
    <Drawer open={!!selected} onClose={() => setSelected(null)} title={selected?.name ?? "Event"} subtitle={`${selected?.timestamp} · ${selected?.source}`}><div className="flex flex-wrap gap-2"><Badge tone={selected?.kind === "Commerce" ? "commerce" : "behavior"}>{selected?.kind}</Badge><Badge tone="success">{selected?.validation}</Badge><Badge>{selected?.authority}</Badge><Badge tone="primary">{selected?.projection}</Badge></div><div className="mt-6"><h3 className="mb-3 text-xs font-medium">Event payload</h3><pre className="scrollbar-thin overflow-auto rounded-lg border bg-background p-4 font-mono text-[11px] leading-6 text-muted-foreground">{JSON.stringify({ event_id: "evt_01J6MX92K", name: selected?.name, source: selected?.source, occurred_at: `2026-08-21T${selected?.timestamp}Z`, session_id: selected?.session, journey_id: selected?.journey, validation: { state: selected?.validation?.toLowerCase(), schema_version: "2.0" }, projection: { state: selected?.projection, watermark_lag_ms: 842 } }, null, 2)}</pre></div></Drawer>
  </>
}
