import { Activity, AlertTriangle, CheckCircle2, Clock3, Gauge, Radio, ShieldCheck, XCircle } from "lucide-react"
import { HealthChart, AnalyticsChart } from "../../components/charts/AnalyticsChart"
import { Badge } from "../../components/ui/badge"
import { ChartCard } from "../../components/ui/chart-card"
import { MetricCard } from "../../components/ui/metric-card"
import { PageHeader } from "../../components/ui/page"

const latencyOption = { xAxis: { type: "category" as const, data: ["p50","p75","p90","p95","p99"], axisLabel: { color: "#7f8494" }, axisLine: { lineStyle: { color: "rgba(148,163,184,.15)" } } }, yAxis: { type: "value" as const, axisLabel: { color: "#7f8494", formatter: "{value}ms" }, splitLine: { lineStyle: { color: "rgba(148,163,184,.08)" } } }, series: [{ type: "bar" as const, data: [82,124,241,388,912], itemStyle: { color: "#3b82f6", borderRadius: [5,5,0,0] }, barWidth: 28 }] }

export function DataHealthPage() {
  return <>
    <PageHeader title="Data health" description="Operational visibility into ingestion, validation, processing latency and reconciliation." badge={<Badge tone="success" dot>Healthy</Badge>} />
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><MetricCard label="Ingestion rate" value="1.8k/s" change={5.2} icon={Radio} data={[8,10,11,13,12,15]} /><MetricCard label="Accepted events" value="99.72%" change={0.4} icon={CheckCircle2} data={[13,14,14,15,15,16]} /><MetricCard label="Rejected events" value="0.21%" change={-12.2} inverse icon={XCircle} data={[16,14,15,12,10,9]} /><MetricCard label="Late events" value="0.07%" change={-4.8} inverse icon={Clock3} data={[12,13,11,10,9,8]} /><MetricCard label="p95 latency" value="388ms" change={-8.1} inverse icon={Gauge} data={[17,16,14,15,12,10]} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)]"><ChartCard title="Events over time" detail="Accepted and rejected events"><HealthChart /></ChartCard><ChartCard title="Processing latency" detail="End-to-end pipeline latency percentiles"><AnalyticsChart option={latencyOption} /></ChartCard></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><ChartCard title="Source health" detail="Current source delivery state" className="xl:col-span-1"><div className="space-y-3">{[["Browser SDK","Healthy","1.2k/s","success"],["Medusa subscriber","Healthy","412/s","success"],["Catalog REST","Warning","48/s","warning"],["Reconciliation","Healthy","6/min","success"]].map(([name,state,rate,tone]) => <div key={name} className="flex items-center gap-3 rounded-lg border p-3"><span className={`h-2 w-2 rounded-full ${tone === "success" ? "bg-success" : "bg-warning"}`} /><div className="flex-1"><strong className="block text-xs">{name}</strong><span className="text-[10px] text-muted-foreground">{rate}</span></div><Badge tone={tone as "success" | "warning"}>{state}</Badge></div>)}</div></ChartCard><ChartCard title="Recent issues" detail="Quality and processing exceptions" className="xl:col-span-2"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-xs"><thead className="text-muted-foreground"><tr className="border-b"><th className="pb-3 font-medium">Issue</th><th className="pb-3 font-medium">Source</th><th className="pb-3 font-medium">Affected</th><th className="pb-3 font-medium">Status</th><th className="pb-3 text-right font-medium">Detected</th></tr></thead><tbody>{[["Catalog snapshot exceeded latency budget","Catalog REST","142 records","Investigating","4m ago"],["Missing source sequence on behavior event","Browser SDK","28 events","Degraded","11m ago"],["Late order event recomputed window","Medusa subscriber","1 journey","Resolved","24m ago"]].map(([issue,source,affected,status,time]) => <tr key={issue} className="border-b last:border-0"><td className="py-3 font-medium">{issue}</td><td>{source}</td><td>{affected}</td><td><Badge tone={status === "Resolved" ? "success" : status === "Degraded" ? "danger" : "warning"}>{status}</Badge></td><td className="text-right text-muted-foreground">{time}</td></tr>)}</tbody></table></div></ChartCard></div>
    <div className="mt-4 panel flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="grid h-10 w-10 place-items-center rounded-lg bg-success/10 text-success"><ShieldCheck size={19} /></div><div className="flex-1"><strong className="text-sm">Reconciliation is converging</strong><p className="mt-1 text-xs text-muted-foreground">99.94% of authoritative order records match current Funnelmetry projections.</p></div><Badge tone="success">Reconciled</Badge></div>
  </>
}
