import { useMemo, useState } from "react"
import { ArrowDown, ArrowUp, Box, Search, ShoppingCart } from "lucide-react"
import { Badge } from "../../components/ui/badge"
import { ChartCard } from "../../components/ui/chart-card"
import { Drawer } from "../../components/ui/drawer"
import { PageHeader } from "../../components/ui/page"
import { compact, money } from "../../lib/utils"
import { products } from "../../mock/data"

type Product = (typeof products)[number]
type SortKey = "name" | "revenue" | "views" | "conversion"

export function ProductsPage() {
  const [query, setQuery] = useState("")
  const [sort, setSort] = useState<SortKey>("revenue")
  const [selected, setSelected] = useState<Product | null>(null)
  const visible = useMemo(() => products.filter((p) => p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b) => typeof a[sort] === "string" ? String(a[sort]).localeCompare(String(b[sort])) : Number(b[sort]) - Number(a[sort])), [query, sort])
  return <>
    <PageHeader title="Products" description="UI preview only. Product attribution and product × window KPI contracts are not finalized yet." badge={<Badge tone="warning">Demo data</Badge>} />
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)]"><ChartCard title="Revenue by product" detail="Demo visualization · not a V2 KPI"><div className="flex h-[270px] items-end gap-3 border-b px-3 pb-6">{products.map((product) => { const max = Math.max(...products.map((item) => item.revenue)); const height = max ? product.revenue / max * 100 : 0; return <div key={product.id} className="flex h-full min-w-0 flex-1 flex-col justify-end gap-2"><div className="w-full rounded-t bg-primary" style={{ height: `${height}%` }} /><span className="truncate text-center text-[9px] text-muted-foreground">{product.name}</span></div> })}</div></ChartCard><ChartCard title="Product contribution" detail="Share of total accepted revenue"><div className="space-y-5 pt-3">{products.slice(0,4).map((p,index) => <div key={p.id}><div className="mb-2 flex justify-between text-xs"><span>{p.name}</span><strong>{[31,24,19,15][index]}%</strong></div><div className="h-2 rounded bg-muted"><div className="h-full rounded bg-primary" style={{ width: `${[31,24,19,15][index]}%`, opacity: 1-index*.13 }} /></div></div>)}</div></ChartCard></div>
    <section className="panel mt-4 overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b p-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold">Product performance</h2><p className="mt-1 text-xs text-muted-foreground">Click a product to inspect its analytics</p></div><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" className="h-9 rounded-lg border bg-background pl-9 pr-3 text-xs" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted/35 text-muted-foreground"><tr>{[["name","Product"],["views","Views"],["cart","Cart additions"],["conversion","Conversion"],["revenue","Revenue"],["trend","Trend"]].map(([key,label]) => <th key={key} className={`px-4 py-3 font-medium ${key === "revenue" || key === "trend" ? "text-right" : ""}`}><button onClick={() => ["name","revenue","views","conversion"].includes(key) && setSort(key as SortKey)} className="inline-flex items-center gap-1">{label}{sort === key && <ArrowDown size={12} />}</button></th>)}</tr></thead><tbody>{visible.map((p) => <tr key={p.id} onClick={() => setSelected(p)} className="cursor-pointer border-b last:border-0 hover:bg-muted/30"><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><Box size={16} /></div><div><strong className="font-medium">{p.name}</strong><span className="block text-[10px] text-muted-foreground">{p.category} · {p.id}</span></div></div></td><td className="px-4">{compact.format(p.views)}</td><td className="px-4">{compact.format(p.cart)}</td><td className="px-4">{p.conversion}%</td><td className="px-4 text-right font-medium">{money.format(p.revenue)}</td><td className={`px-4 text-right ${p.trend > 0 ? "text-success" : "text-destructive"}`}>{p.trend > 0 ? "+" : ""}{p.trend}%</td></tr>)}</tbody></table></div></section>
    <Drawer open={!!selected} onClose={() => setSelected(null)} title={selected?.name ?? "Product"} subtitle={`${selected?.category} · ${selected?.id}`}><div className="grid grid-cols-2 gap-3">{[["Revenue",money.format(selected?.revenue ?? 0)],["Views",compact.format(selected?.views ?? 0)],["Cart additions",compact.format(selected?.cart ?? 0)],["Conversion",`${selected?.conversion}%`]].map(([label,value]) => <div key={label} className="rounded-lg border p-3"><span className="text-[10px] text-muted-foreground">{label}</span><strong className="mt-1 block text-lg">{value}</strong></div>)}</div><div className="mt-6"><h3 className="mb-3 text-xs font-medium">Conversion path</h3>{[["Product viewed",100],["Cart item added",36],["Checkout contribution",21],["Order contribution",8]].map(([label,value]) => <div key={String(label)} className="mb-4"><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{value}%</strong></div><div className="h-2 rounded bg-muted"><div className="h-full rounded bg-primary" style={{ width: `${value}%` }} /></div></div>)}</div><div className="mt-6 rounded-lg border bg-muted/20 p-4 text-xs"><ShoppingCart size={17} className="mb-2 text-primary" /><strong>Checkout opportunity</strong><p className="mt-1 leading-5 text-muted-foreground">Mobile cart-to-checkout conversion is 11.2% below desktop for this product.</p></div></Drawer>
  </>
}
