apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-processor
  namespace: realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-processor
  template:
    metadata:
      labels:
        app: streaming-processor
    spec:
      containers:
        - name: streaming-processor
          image: streaming-processor:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC_RAW
              value: tracking_events_raw
            - name: KAFKA_GROUP_ID
              value: streaming-processor
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: FLUSH_INTERVAL_SEC
              value: "30"
            - name: EVENT_BATCH_SIZE
              value: "100"
            - name: QDRANT_URL
              value: ""
            - name: QDRANT_COLLECTION
              value: pipeline_insights
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
