import { useMemo, useState } from "react"
import { ArrowRight, CalendarDays, Clock3, Search, Split, UserRound } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { Badge } from "../../components/ui/badge"
import { Button } from "../../components/ui/button"
import { PageHeader } from "../../components/ui/page"
import { journeySessions } from "../../mock/data"

const journeys = [
  { id: "journey_10021", sessions: 3, duration: "7 days", source: "Paid social", outcome: "Converted", device: "Mobile → Desktop" },
  { id: "journey_10308", sessions: 2, duration: "3 days", source: "Organic", outcome: "Checkout", device: "Desktop" },
  { id: "journey_10277", sessions: 4, duration: "12 days", source: "Referral", outcome: "Payment retry", device: "Mobile" },
  { id: "journey_10098", sessions: 1, duration: "18 min", source: "Direct", outcome: "Converted", device: "Desktop" },
]

export function JourneysPage() {
  const [query, setQuery] = useState("")
  const [selected, setSelected] = useState(journeys[0])
  const navigate = useNavigate()
  const visible = useMemo(() => journeys.filter((j) => j.id.includes(query.toLowerCase())), [query])
  return <>
    <PageHeader title="Journey explorer" description="Explore a customer journey across multiple sessions. A journey is not a session; it can continue across days and devices." badge={<Badge tone="primary">Cross-session</Badge>} />
    <div className="grid gap-4 xl:grid-cols-[340px_minmax(0,1fr)]">
      <aside className="panel overflow-hidden"><div className="border-b p-4"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search journey ID" className="h-9 w-full rounded-lg border bg-background pl-9 pr-3 text-xs" /></div></div><div className="max-h-[690px] overflow-y-auto p-2">{visible.map((journey) => <button key={journey.id} onClick={() => setSelected(journey)} className={`mb-1 w-full rounded-lg border p-3 text-left transition ${selected.id === journey.id ? "border-primary/40 bg-primary/10" : "border-transparent hover:bg-muted"}`}><div className="flex items-center justify-between"><strong className="font-mono text-xs">{journey.id}</strong><Badge tone={journey.outcome === "Converted" ? "success" : "warning"}>{journey.outcome}</Badge></div><div className="mt-3 flex gap-4 text-[10px] text-muted-foreground"><span>{journey.sessions} sessions</span><span>{journey.duration}</span><span>{journey.source}</span></div></button>)}</div></aside>
      <section className="panel p-5 md:p-6"><div className="flex flex-col justify-between gap-4 border-b pb-5 md:flex-row md:items-start"><div><p className="eyebrow">Journey</p><h2 className="mt-2 font-mono text-xl font-semibold">{selected.id}</h2><div className="mt-3 flex flex-wrap gap-2"><Badge tone="success" dot>{selected.outcome}</Badge><Badge>{selected.device}</Badge><Badge>{selected.source}</Badge></div></div><div className="grid grid-cols-3 gap-5 text-center"><div><strong className="block text-xl">{selected.sessions}</strong><span className="text-[10px] text-muted-foreground">Sessions</span></div><div><strong className="block text-xl">{selected.duration}</strong><span className="text-[10px] text-muted-foreground">Journey span</span></div><div><strong className="block text-xl">8</strong><span className="text-[10px] text-muted-foreground">Events</span></div></div></div>
        <div className="mt-6"><div className="mb-6 flex items-center gap-2 text-xs text-muted-foreground"><Split size={15} /><strong className="text-foreground">One journey</strong><span>linked across {journeySessions.length} sessions</span></div><div className="relative ml-3 border-l border-border pl-7">{journeySessions.map((session, index) => <article key={session.id} className="relative mb-8 last:mb-0"><span className={`absolute -left-[35px] top-0 grid h-4 w-4 place-items-center rounded-full border-4 border-card ${index === journeySessions.length - 1 ? "bg-success" : "bg-primary"}`} /><div className="panel panel-hover p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><strong className="text-sm">{session.label}</strong><span className="text-xs text-muted-foreground">{session.day}</span></div><button className="mt-1 font-mono text-[11px] text-primary hover:underline" onClick={() => navigate(`/sessions/${session.id}`)}>{session.id}</button></div><div className="flex items-center gap-2"><Badge tone={session.outcome === "Converted" ? "success" : session.outcome.includes("abandoned") ? "warning" : "neutral"}>{session.outcome}</Badge><Button variant="ghost" size="sm" onClick={() => navigate(`/sessions/${session.id}`)}>Inspect <ArrowRight size={13} /></Button></div></div><p className="mt-3 text-xs text-muted-foreground">{session.meta}</p><div className="mt-4 flex flex-wrap items-center gap-2">{session.events.map((event, eventIndex) => <div key={`${event}-${eventIndex}`} className="flex items-center gap-2"><span className={`rounded-md border px-2 py-1 font-mono text-[10px] ${event.startsWith("order") || event.startsWith("payment") || event.startsWith("cart") ? "border-emerald-500/20 bg-emerald-500/5 text-emerald-400" : "bg-muted text-muted-foreground"}`}>{event}</span>{eventIndex < session.events.length - 1 && <ArrowRight size={11} className="text-muted-foreground" />}</div>)}</div></div>{index < journeySessions.length - 1 && <div className="my-3 flex items-center gap-2 text-[10px] text-muted-foreground"><Clock3 size={12} />{index === 0 ? "2 days later" : "5 days later"}</div>}</article>)}</div></div>
        <div className="mt-8 grid gap-3 border-t pt-5 sm:grid-cols-3"><div className="rounded-lg bg-muted/40 p-3"><CalendarDays size={15} className="mb-2 text-primary" /><span className="block text-[10px] text-muted-foreground">First seen</span><strong className="text-xs">Aug 14, 09:24</strong></div><div className="rounded-lg bg-muted/40 p-3"><UserRound size={15} className="mb-2 text-primary" /><span className="block text-[10px] text-muted-foreground">Identity link</span><strong className="text-xs">Cart + order key</strong></div><div className="rounded-lg bg-muted/40 p-3"><Clock3 size={15} className="mb-2 text-primary" /><span className="block text-[10px] text-muted-foreground">Confidence</span><strong className="text-xs">High · 96%</strong></div></div>
      </section>
    </div>
  </>
}
