apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sprint1
  - ../data/qdrant
  - ../apps/dashboard-api
  - ../apps/dashboard-ui
  - ../apps/ollama

patches:
  - path: patch-streaming-qdrant.yaml
  - path: patch-tracking-api-nodeport.yaml
